#! /bin/bash

hora=$(date '+%H')
dir="/home/$USER/Imagens/mojave"

case $hora in

00 | 01 | 02) imagem="16";;

03 | 04) imagem="1";;

05) imagem="2";;
06) imagem="3";;
07) imagem="4";;
08) imagem="5";;
09) imagem="6";;
10) imagem="7";;

11 | 12) imagem="8";;

13) imagem="9";;
14) imagem="10";;
15) imagem="11";;
16) imagem="12";;
17) imagem="13";;

18 | 19) imagem="14";;

20 | 21 | 22 | 23) imagem="15";;
esac

xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "$dir/$imagem.jpeg"

xfdesktop --reload
